# Default values for okta-react-sample

image:
  repository: "nginx"   # UPDATED at deploy-time by GitHub Actions workflow
  tag: "latest"         # UPDATED at deploy-time
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

replicaCount: 2

resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

# Uncomment to configure ingress
# ingress:
#   enabled: false
#   className: ""
#   annotations: {}
#   hosts:
#     - host: chart-example.local
#       paths:
#         - /
#   tls: []
