apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "okta-react-sample.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "okta-react-sample.name" . }}
    helm.sh/chart: {{ include "okta-react-sample.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "okta-react-sample.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "okta-react-sample.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .values.serviceAccount.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .values.image.repository }}:{{ .values.image.tag }}"
          imagePullPolicy: {{ .values.image.pullPolicy }}
          ports:
            - containerPort: {{ .values.containerPort }}
          # add other container configuration here
